apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - rbac.yml
  - network-policy.yml

configMapGenerator:
  - name: cassandra-config
    files:
      - ./cassandra/trustStore.jks
      - ./cassandra/identity.jks