apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  selector:
    app: hello
  publishNotReadyAddresses: true
  ports:
    - name: "http"
      port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-stream
  labels:
    app: hello-stream
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  selector:
    app: hello-stream
  publishNotReadyAddresses: true
  ports:
    - name: "http"
      port: 9000