apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  selector:
    app: hello
  publishNotReadyAddresses: true
  ports:
    - name: "http"
      port: 9000
      targetPort: 9000
    - name: "akka-remote"
      port: 10001
      protocol: TCP
      targetPort: 10001
    - name: "akka-mgmt-http"
      port: 10003
      protocol: TCP
      targetPort: 10003
---
apiVersion: v1
kind: Service
metadata:
  name: hello-stream
  labels:
    app: hello-stream
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  selector:
    app: hello-stream
  publishNotReadyAddresses: true
  ports:
    - name: "http"
      port: 9001
      targetPort: 9001
    - name: "akka-remote"
      port: 10002
      protocol: TCP
      targetPort: 10002
    - name: "akka-mgmt-http"
      port: 10004
      protocol: TCP
      targetPort: 10004