apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
        - name: hello
          env:
            - name: JAVA_OPTS
              value: "-Dconfig.resource=prod-application.conf"
            - name: CASSANDRA_SERVICE_NAME
              value: _cql._tcp.cassandra.default.svc.cluster.local
            - name: CASSANDRA_USERNAME
              value: cassandra
            - name: CASSANDRA_PASSWORD
              value: wFdniRalR5
            - name: KAFKA_SERVICE_NAME
              value: _tcp-clients._tcp.strimzi-kafka-brokers.kafka.svc.cluster.local
            - name: PLAY_HTTP_SECRET_KEY
              value: ZPFv7e27x7dZalf9SNR7uXbCmUaghqzh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-stream
spec:
  template:
    spec:
      containers:
        - name: hello-stream
          env:
            - name: KAFKA_SERVICE_NAME
              value: _tcp-clients._tcp.strimzi-kafka-brokers.kafka.svc.cluster.local