apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - deployment.yml

configMapGenerator:
  - name: cassandra-config
    files:
      - ./cassandra/trustStore.jks
      - ./cassandra/identity.jks